
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

# [[main]]
#   name = "Experiments & Exploration"  # Title of the link.
#   url = "experiments/"  # Widget Page folder name.
#   weight = 20  # Position of the link in the navigation bar.

[[main]]
  name = "Paper Summaries"  # Title of the link.
  url = "paper_summaries/"  # Widget Page folder name.
  weight = 30  # Position of the link in the navigation bar.

[[main]]
  name = "Notes"  # Title of the link.
  url = "notes/"  # Widget Page folder name.
  weight = 40  # Position of the link in the navigation bar.

[[main]]
  name = "Posts"  # Title of the link.
  url = "posts/"  # Widget Page folder name.
  weight = 50  # Position of the link in the navigation bar.

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
